### ISSUE TITLE
Unhandled Exception with GUI despite multiple un- and re-installs

### ISSUE THREAD

**Issue by Zerrvr** [chocolatey/ChocolateyGUI#1021]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I try to open the GUI, and it throws a very large unhandled exception. I tried un- and re-installing the GUI, chocolatey, and various packages, but nothing seems to work.

### What is Expected?

The GUI should open and load packages as normal

### How Did You Get This To Happen?

I updated Firefox to 116 from within the GUI, and that's when the issue started.

### System Details

* Operating System: 10.0.22621.0
* Windows PowerShell version: 5.1.22621.1778
* Chocolatey CLI Version: 2.2.0
* Chocolatey Licensed Extension version: Chocolatey v2.2.0
* Chocolatey License type: ?
* Terminal/Emulator:  Windows PowerShell

### Installed Packages

```bash
7zip.install 22.1.0
amazon-workspaces 5.8.0.4065
amd-ryzen-master 2.10.1.2287
autohotkey 1.1.36.2
autohotkey.install 1.1.36.2
autohotkey.portable 2.0.2
calibre 6.22.0
caprine 2.57.0
chocolatey 2.2.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolateygui 2.1.0
chocolatey-windowsupdate.extension 1.0.5
discord.install 1.0.9005
dotnet-6.0-desktopruntime 6.0.14
dotnet-7.0-desktopruntime 7.0.3
dotnet-desktopruntime 7.0.3
dotnetfx 4.8.0.20220524
Firefox 116.0.0
goxlr 1.3.3.13001
handbrake 1.6.1
handbrake.install 1.6.1
hwinfo.install 7.60.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
microsoft-teams 1.6.0.6754
msiafterburner 4.6.5
netfx-4.7.2 4.7.2
notepadplusplus.install 8.4.9
paint.net 5.0.2
powertoys 0.68.0
python3 3.11.0
qbittorrent 4.5.4
sharex 15.0.0
slack 4.29.149
steam 2.10.91.91221129
streamdeck 6.0.5.18168
superf4 1.4.0
vcredist140 14.34.31938
vcredist2010 10.0.40219.32503
vcredist2015 14.0.24215.20170201
wiztree 4.13.0
yt-dlp 2023.6.22
zoom 5.13.10.13305
```

### Output Log

```bash
https://gist.github.com/Zerrvr/dcf5945194104f93fbcd64b637513837
```

### Additional Context

The error message is as follows:

```
/---------------------------
Unhandled Exception
---------------------------
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)

   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()

   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()

   at System.Xml.XmlReader.MoveToContent()

   at System.Xml.XmlReader.IsStartElement(String localname, String ns)

   at chocolatey.infrastructure.services.XmlService.<>c__DisplayClass5_0`1.<Deserialize>b__2()

   at chocolatey.infrastructure.tolerance.FaultTolerance.TryCatchWithLoggingException[T](Func`1 function, String errorMessage, Boolean throwError, Boolean logWarningInsteadOfError, Boolean logDebugInsteadOfError, Boolean isSilent)

   at chocolatey.infrastructure.services.XmlService.<>c__DisplayClass5_0`1.<Deserialize>b__1()

   at chocolatey.infrastructure.synchronization.GlobalMutex.Enter[T](Func`1 func, Int32 timeout)

   at chocolatey.infrastructure.tolerance.FaultTolerance.Retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)

   at chocolatey.infrastructure.services.XmlService.Deserialize[XmlType](String xmlFilePath, Int32 retryCount)

   at ChocolateyGui.Common.Windows.Services.ChocolateyService.<GetOutdatedPackages>d__13.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Services\ChocolateyService.cs:line 121

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ChocolateyGui.Common.Windows.ViewModels.LocalSourceViewModel.<CheckOutdated>d__81.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\ViewModels\LocalSourceViewModel.cs:line 494

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ChocolateyGui.Common.Windows.ViewModels.LocalSourceViewModel.<LoadPackages>d__80.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\ViewModels\LocalSourceViewModel.cs:line 470

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ChocolateyGui.Common.Windows.ViewModels.LocalSourceViewModel.<OnInitialize>d__78.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\ViewModels\LocalSourceViewModel.cs:line 412

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at ChocolateyGui.App.Main(String[] args) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui\App.xaml.cs:line 122
---------------------------
OK   
---------------------------
```

**Comment by pauby** [comment]
@Zerrvr it's been a while since this issue. I'm unable to replicate it. Are you still having this issue with the latest version of ChocolateyGUI?

**Comment by justdanpo** [comment]
@Zerrvr could you please reopen the issue?
I was able to unintentionally reproduce it. In my case `AppData\Local\Chocolatey GUI\outdatedPackages.xml` got broken after a sudden power off and contained only zero bytes in it.

**Comment by pauby** [comment]
@justdanpo this issue was closed automatically 2 months ago. Please raise a new issue and complete all sections to allow us to capture the required information.
