### ISSUE TITLE
Crashes when updating available packages from an internal Nuget feed

### ISSUE THREAD

**Issue by insanity54** [chocolatey/ChocolateyGUI#415]
## Observed Error Message

```
---------------------------
Unhandled Exception
---------------------------
System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: Only DELETEs allowed here
   at System.Data.Services.Client.QueryResult.ExecuteQuery()
   at System.Data.Services.Client.DataServiceRequest.GetQuerySetCount(DataServiceContext context)
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.DataServiceRequest.GetQuerySetCount(DataServiceContext context)
   at System.Data.Services.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at ChocolateyGui.Services.PackageServices.ODataPackageService.<Search>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.PackageService.<Search>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.Controls.RemoteSourceControlViewModel.<LoadPackages>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ChocolateyGui.App.Main()
---------------------------
OK   
---------------------------
```

## Steps to reproduce:

* open ChocolateyGUI
* click settings
* add source 'http://nuget.xxxxxx.net/' with name 'company name'
* close settings
* click 'company name' on source selection (left column)
* crash

## Software Info

Windows 7 x64 SP1
Powershell v 3.0
.NET v4.5.1
Chocolatey v0.10.3
ChocolateyGUI v0.13.2.0

Nuget Server (Docker) sunside/simple-nuget-server 0.5

**Comment by RichiCoder1** [comment]
Huh, that's bizzare. Buuut, it should also be fixed in prerelease.

**Comment by insanity54** [comment]
I just tried doing the same in prerelease v0.15.0-unstable0241, and there was no crash. Thanks.
