### ISSUE TITLE
NullRefEx on launch

### ISSUE THREAD

**Issue by chucker** [chocolatey/ChocolateyGUI#440]
```
System.NullReferenceException: Object reference not set to an instance of an object.
at ChocolateyGui.SenricesCliocolateyRemotePackageService.<GetSources>d_24.MoveNext() in
C:\projects\chocolateygui\Source\ChocolateyGui\Senrices\ChocolateyRemotePackageService.<xline 246
——— End of stack trace from previous location where exception was thrown ———
at System.Ru ntime.Com pilerServicesTaskAwaiter.ThrowForNonSuccess(T ask task)
at System.Ru ntime.Com pilerServicesTaskAwaiter.HandleNonSuccessAnd DebuggerNotification(T ask task)
at ChocolateyGui.ViewModels.ShellViewModel.<GetSources>d_2?.MoveNext() in C.‘\projects\chocolateygui\Source\ChocolateyGui\ViewModels\ShellViewModelﬁline 134
——— End of stack trace from previous location where exception was thrown ———
at System.Runtime.CompilerSeNicesAsyncMethodBuilderCore.< >c<ThrowAsync>b_6_0(Object state)
at System.Windows.Threading.ExceptionWrapper.lnternalRealCall(Delegate callback, Object args, lnt32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, lnt32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperatiorLlnvokelmplt)
at System.Windows.Threading.DispatcherOperatiorLlnvokelnSecurityConten(Object state)
at System.Threading.ExecutionContext.Runlnternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at MSInternaLCulturePresenringExecutionContexLRun(CulturePreservingExecutionConten executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperatiorLlnvoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(lntPtr hwnd, lnt32 msg, lntPtr wParam, lntPtr lParam, BooleanBL handled)
at MSWin32.HwndWrapper.WndProc(lntPtr hwnd, lnt32 msg, lntPtr wParam, lntPtr lParam, BooleanBL handled)
at MSWin32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.lnternalRealCall(Delegate callback, Object args, lnt32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, lnt32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.Legacylnvokelmpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, lnt32 numArgs)
at MSWin32.HwndSubclass.SubclassWndProc(lntPtr hwnd, lnt32 msg, lntPtr wParam, lntPtr lParam)
at MSWin32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFramelmpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.ApplicatiorLRunDispatcher(Object ignore)
at System.Windows.ApplicatiorLRunlnternal(Window window)
at System.Windows.ApplicatiorLRun(Window window)
at ChocolateyGuiApp.Main(String[] args) in C.‘\projects\chocolateygui\Source\ChocolateyGui\App.xaml.<xline 39

```

(Note that I OCR'd the above stacktrace, so some characters are off.)

I get this immediately after launch. I've already tried deleting `%localappdata%\ChocolateyGUI` to no avail. No logs are created during this launch in either `\programdata\chocolatey\logs` or `%appdata%\ChocolateyGUI\Logs`.

**Comment by chucker** [comment]
Not sure why I didn't think before to check `%programdata%\ChocolateyGUI`. The subprocess log just says this:

```
2017-06-07 22:28:55.257 +02:00 [Information] Starting Chocolatey Server.
2017-06-07 22:28:55.382 +02:00 [Information] Started chocolatey server.
2017-06-07 22:29:05.413 +02:00 [Information] Stopping Chocolatey Server.
```

The other log apparently fails to create a named pipe:

```
2017-06-07 22:28:55.257 +02:00 [Fatal] Failed to create client channel to server.
System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at net.pipe://localhost/chocolateygui that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.IO.PipeException: The pipe endpoint 'net.pipe://localhost/chocolateygui' could not be found on your local machine. 
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.PipeConnectionInitiator.GetPipeName(Uri uri, IPipeTransportFactorySettings transportFactorySettings)
   at System.ServiceModel.Channels.NamedPipeConnectionPoolRegistry.NamedPipeConnectionPool.GetPoolKey(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.CommunicationPool`2.TakeConnection(EndpointAddress address, Uri via, TimeSpan timeout, TKey& key)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ChocolateyGui.IIpcChocolateyService.Register()
   at ChocolateyGui.Services.ChocolateyRemotePackageService.CreateClient() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 411
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<InitializeImpl>d__32.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<Initialize>d__31.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<GetSources>d__24.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.SourcesViewModel.<LoadSources>d__5.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\ViewModels\SourcesViewModel.cs:line 62
2017-06-07 22:28:55.288 +02:00 [Fatal] Failed to initialize the chocolatey server.
System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at net.pipe://localhost/chocolateygui that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.IO.PipeException: The pipe endpoint 'net.pipe://localhost/chocolateygui' could not be found on your local machine. 
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.PipeConnectionInitiator.GetPipeName(Uri uri, IPipeTransportFactorySettings transportFactorySettings)
   at System.ServiceModel.Channels.NamedPipeConnectionPoolRegistry.NamedPipeConnectionPool.GetPoolKey(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.CommunicationPool`2.TakeConnection(EndpointAddress address, Uri via, TimeSpan timeout, TKey& key)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ChocolateyGui.IIpcChocolateyService.Register()
   at ChocolateyGui.Services.ChocolateyRemotePackageService.CreateClient() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 411
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<InitializeImpl>d__32.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<Initialize>d__31.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<GetSources>d__24.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.SourcesViewModel.<LoadSources>d__5.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\ViewModels\SourcesViewModel.cs:line 62
2017-06-07 22:28:56.007 +02:00 [Fatal] Packages failed to load
2017-06-07 22:28:56.007 +02:00 [Fatal] Local source control view model failed to load.
2017-06-07 22:28:56.532 +02:00 [Fatal] Unhandled Exception
```

Machine runs Windows Server 2012 R2 and is a terminal server.

**Comment by RichiCoder1** [comment]
Could you try the lastest? I just ran into a similair issue myself and switched how we handle IPC

**Comment by chucker** [comment]
Unfortunately, I now get a crash even earlier, see #447.

**Comment by mwallner** [comment]
can confirm this still happens with current develop. (eb464a1381ce19a5d9d2b3904876fb06045f14ec)
![07dc77c6d06bb550a6395882d92de069f2814b65ad312e47b7 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/5354972/26963813-c42ed374-4cee-11e7-8365-b8aba3f965be.png)

**Comment by gep13** [comment]
@chucker @mwallner I am fairly sure that this has now been addressed as a result of the refactoring away from using the Chocolatey Sub Process.  I am away to close this issue, but please feel free to re-open if you still see issues.
