### ISSUE TITLE
FileLoadException on launch

### ISSUE THREAD

**Issue by chucker** [chocolatey/ChocolateyGUI#447]
From Windows Event Log:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at ChocolateyGui.Bootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at ChocolateyGui.Bootstrapper..ctor()
```

Occurs in 0.14.0-unstable0269 und 0280. 0261 was not affected.

**Comment by RichiCoder1** [comment]
Hmm. Maybe I'm not shipping a DLL I should be? Or a wrong one? Will look into it.

**Comment by chucker** [comment]
Problem appears to be Autofac. From Fusion Log Viewer:

```
LOG: Post-policy reference: Autofac, Version=4.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/ChocolateyGUI/Autofac.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files (x86)\ChocolateyGUI\Autofac.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Autofac, Version=4.6.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by RichiCoder1** [comment]
Let me know if you're still seeing this issue with the latest pre @chucker

**Comment by chucker** [comment]
Nope. Fixed, thanks!
