### ISSUE TITLE
Access Denied on Launch

### ISSUE THREAD

**Issue by TheVakman** [chocolatey/ChocolateyGUI#460]
On most of my test machines, ChocolateyGUI can be opened by a non-administrator, whether or not they can install packages from the sources.

On one system, it crashes with "Access Denied" (see log below). 
If I launch it as an administrator on the same machine, it runs as expected.

This is on a 0.14 release.

```
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<InitializeImpl>d__32.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<Initialize>d__31.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<GetSources>d__24.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 257
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.SourcesViewModel.<LoadSources>d__5.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\ViewModels\SourcesViewModel.cs:line 62
2017-08-31 07:48:14.683 -04:00 [Fatal] Failed to initialize the chocolatey server.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<InitializeImpl>d__32.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<Initialize>d__31.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<GetSources>d__24.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 257
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.ShellViewModel.<GetSources>d__27.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\ViewModels\ShellViewModel.cs:line 134
2017-08-31 07:48:15.117 -04:00 [Fatal] Failed to initialize the chocolatey server.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<InitializeImpl>d__32.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<Initialize>d__31.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.Services.ChocolateyRemotePackageService.<GetInstalledPackages>d__13.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\Services\ChocolateyRemotePackageService.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChocolateyGui.ViewModels.LocalSourceViewModel.<LoadPackages>d__50.MoveNext() in C:\projects\chocolateygui\Source\ChocolateyGui\ViewModels\LocalSourceViewModel.cs:line 293
2017-08-31 07:48:15.118 -04:00 [Fatal] Packages failed to load
2017-08-31 07:48:15.118 -04:00 [Fatal] Local source control view model failed to load.
2017-08-31 07:48:15.639 -04:00 [Fatal] Unhandled Exception

```

**Comment by TheVakman** [comment]
I installed from the MyGet repository at the time. I can again update now.
0.14.0-unstable.290+Branch.develop - not sure if that's good enough.

Also, thanks for adding the versions back in!

**Comment by RichiCoder1** [comment]
We've moved away from the process model that was causing this issue. Let me know if you're still running into this with the latest prerelease!
