### ISSUE TITLE
Failed to Start Application (LogMessage)

### ISSUE THREAD

**Issue by TheVakman** [chocolatey/ChocolateyGUI#461]
On one test system (running a 0.14 release), this error started to occur. ChocolateyGUI was previously functional but now it crashes immediately upon startup.

```
2017-08-31 07:46:28.563 -04:00 [Fatal] Failed to start application.
System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: The operation 'LogMessage' could not be completed because the sessionful channel timed out waiting to receive a message.  To increase the timeout, either set the receiveTimeout property on the binding in your configuration file, or set the ReceiveTimeout property on the Binding directly. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ServiceModel.CommunicationObjectAbortedException: The operation 'LogMessage' could not be completed because the sessionful channel timed out waiting to receive a message.  To increase the timeout, either set the receiveTimeout property on the binding in your configuration file, or set the ReceiveTimeout property on the Binding directly.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfIdleAborted(ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealPr...).
```

**Comment by mwallner** [comment]
Hallo @TheVakman , thanks for the report - can you be a bit more specific concerning the version of ChocolateyGUI you're using? (maybe even a commit hash?) - where did you install from?

**Comment by TheVakman** [comment]
I installed from the MyGet repository at the time. I can again update now.
0.14.0-unstable.290+Branch.develop - not sure if that's good enough.

Also, thanks for adding the versions back in!

**Comment by RichiCoder1** [comment]
Is chocolatey itself still performing normally?

**Comment by TheVakman** [comment]
Sorry, I forgot to reply. Yes, it is - completely functional.

However, I think we can close this. I was able to reproduce consistently but the .300 release doesn't seem to have this issue for me. It's also possible that the uninstall/reinstall fixed the issue.
