### ISSUE TITLE
Source credential changes outside of Chocolatey GUI cause issues

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#494]
If a source is changed to require credentials and the source configuration is not changed prior to opening Chocolatey GUI, it errors on opening as it is attempting to check for updated packages and the source keeps asking for credentials.

**Comment by ferventcoder** [comment]
I would hope that Chocolatey GUI recognizes the issue and stops attempting to use that source (and then places a little red background on it in the sources tab). Maybe an alerts section as well to let folks know something is wrong.

**Comment by RichiCoder1** [comment]
Gui is currently very unreactive to outside changes once started. One of my next things I want to tackle.

**Comment by ferventcoder** [comment]
Sorry for the confusion. If you change the source to require credentials, and ***then*** you open Chocolatey GUI, hoping to go update the source with the credentials, you are SOL and must do it from the command line.

**Comment by RichiCoder1** [comment]
Ah. I'll look into that now

**Comment by ferventcoder** [comment]
I believe this is likely still an issue unless it opens a dialog when requested.

**Comment by ryanrichter94** [comment]
Can confirm that this is still an issue when using Chocolatey V 1.1.0 and Chocolatey GUI V 1.0.0 

When attempting to load Chocolatey GUI while having an authenticated source with no saved authentication in the source config of Chocolatey. Chocolatey GUI will open to the splash screen and then stop with a `[Fatal] Unhandled Exception` error in the Chocolatey GUI log. 

Full relevant info from Chocolatey GUI log output:

```
2022-06-24 08:08:18.986 -07:00 [Information] Please provide credentials for: https://Testy:8443/repository/ChocolateyInternal/
2022-06-24 08:08:19.007 -07:00 [Fatal] Unhandled Exception
```

**Comment by ryanrichter94** [comment]
Additional error info from Window event viewer

![image](https://user-images.githubusercontent.com/57045117/175627799-2c817404-27ee-4b80-86a2-8cd58c9b701e.png)

Error text itself:

```
Application: chocolateygui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Console.ReadKey(Boolean)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.console_read_key()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
