### ISSUE TITLE
Unhandled LicenseExpiredException

### ISSUE THREAD

**Issue by HolisticDeveloper** [chocolatey/ChocolateyGUI#594]
My Chocolatey Pro license expired a few days ago (working on getting it renewed) but this seems to be causing an issue for ChocolateyGUI. Should ChocolateyGUI still work even with an expired license?

After leaving ChocoatelyGUI idle for a few minutes, I repeatedly get a message box with this error:

Rhino.Licensing.LicenseExpiredException: Expiration Date : 6/1/2018 12:00:00 AM
   at Rhino.Licensing.AbstractLicenseValidator.HasExistingLicense() in D:\Coding\Projects\GitHub\alphafs\AlphaFS\Filesystem\File Class\File.GetAttributes.cs:line 0
   at Rhino.Licensing.AbstractLicenseValidator.LeaseLicenseAgain(Object state) in D:\Coding\Projects\GitHub\alphafs\AlphaFS\Filesystem\File Class\File.GetAttributes.cs:line 0
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

or sometimes this one:

Rhino.Licensing.LicenseExpiredException: Expiration Date : 6/1/2018 12:00:00 AM
   at Rhino.Licensing.AbstractLicenseValidator.HasExistingLicense() in D:\Coding\Projects\GitHub\alphafs\AlphaFS\Filesystem\File Class\File.GetAttributes.cs:line 0
   at Rhino.Licensing.AbstractLicenseValidator.LeaseLicenseAgain(Object state) in D:\Coding\Projects\GitHub\alphafs\AlphaFS\Filesystem\File Class\File.GetAttributes.cs:line 0
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Eventually after dismissing these a bunch of times, ChocolateyGUI closes and then after a while the error messages eventually stop.

Obviously I can remove my license file, but it seems ChocolateyGUI should handle this more gracefully?

**Comment by HolisticDeveloper** [comment]
Ah, I think this is coming from chocolatey itself. I get the same exception if I leave chocolatey idle at the "Do you want to run the script?" prompt in a powershell window.

**Comment by ferventcoder** [comment]
Duplicate for sure. I want to say we've fixed this issue, but it may not have made it into GUI codebase yet.

**Comment by ferventcoder** [comment]
Duplicate of https://github.com/chocolatey/choco/issues/1500

**Comment by ferventcoder** [comment]
This also requires being on at least 1.12.12 of Chocolatey Licensed Extension as well - https://chocolatey.org/docs/release-notes-licensed#june-12-2018
