### ISSUE TITLE
Unhandled Exception - System.InvalidOperationException - annot read keys when either application does not have a console or when console input has been redirected from a file

### ISSUE THREAD

**Issue by manuc66** [chocolatey/ChocolateyGUI#798]
Hi,

I'm launching the GUI and it keep crashing with this message:
```
---------------------------
Unhandled Exception
---------------------------
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.

   at System.Console.ReadKey(Boolean intercept)

   at chocolatey.infrastructure.commandline.ReadKeyTimeout.console_read_key() in c:\codelocal\chocolatey2\src\chocolatey\infrastructure\commandline\ReadKeyTimeout.cs:line 54

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()
---------------------------
OK   
---------------------------
```

It is probably due to the fact that the nuget server user is requiring a password:
![image](https://user-images.githubusercontent.com/5827164/101880593-79862d80-3b93-11eb-82ea-e105132d8d7d.png)

**Comment by manuc66** [comment]
Disabling the package source with the command line was a workaround, but I wouldn't have expected the GUI to crash

**Comment by gep13** [comment]
A crash in the Chocolatey GUI is certainly not ideal, no.

Is there any reason that you haven't stored the username/password for the source via the `choco source add` command?

That should then allow the source to be viewed in Chocolatey GUI.

**Comment by manuc66** [comment]
I may have configured the feed from the GUI

**Comment by Niko31789** [comment]
Hi everyone, I wonder if this issue has been solved. I am facing same issue, however I chose not to store the username/password for the source as I have 2 repositories and one only visible to certain people (LDAP security group added) and the other by admin only.

**Comment by samhocevar** [comment]
Same problem here. The GUI crashes because my credentials have changed, before I can go to the settings to update the password.

**Comment by AdmiringWorm** [comment]
As this will require changes in Chocolatey CLI to prevent this exception to occur, a issue for Chocolatey CLI has been created for tracking purposes here: https://github.com/chocolatey/choco/issues/2805
