### ISSUE TITLE
The icons are not shown anymore

### ISSUE THREAD

**Issue by aminya** [chocolatey/ChocolateyGUI#849]
chocolatey-gui 0.18.1

![image](https://user-images.githubusercontent.com/16418197/115957659-5ec0af80-a4c9-11eb-96e4-330bcd7678f4.png)

**Comment by gep13** [comment]
@aminya sorry to hear that you are having problems.  

Is that screen shot of the "This PC" tab?

This can happen when there isn't an internet connection, and the icons aren't able to be downloaded.

**Comment by aminya** [comment]
I have been having this problem for so long. I do have access to the internet.

**Comment by aminya** [comment]
Here is the log I found in `ChocolateyGui.20210619.log`
```c#

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2021-06-19 14:11:17.824 -05:00 [Warning] Something went wrong with: "https://assets.onestore.ms/cdnfiles/onestorerolling-1509-17011/shell/v1_2/images/logo/microsoft.png".
System.IO.FileLoadException: Could not load file or assembly 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=dfd1909b30b79d8b' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=dfd1909b30b79d8b'
   at ChocolateyGui.Common.Windows.Services.PackageIconService.GetImage(String url, Size desiredSize, DateTime absoluteExpiration)
   at ChocolateyGui.Common.Windows.Controls.InternetImage.<SetImage>d__7.MoveNext() in C:\github_local\organisations\chocolatey\ChocolateyGUI\Source\ChocolateyGui.Common.Windows\Controls\InternetImage.xaml.cs:line 64
```

**Comment by aminya** [comment]
Uninstalling ChocolateyGUI with Revo uninstaller and reinstalling it fixed the problem.
