### ISSUE TITLE
System.Exception: Method Pin on type MS.Internal.NamedObject does not have a valid method signature

### ISSUE THREAD

**Issue by jmacura** [chocolatey/ChocolateyGUI#922]
### What You Are Seeing?
![obrazek](https://user-images.githubusercontent.com/5598693/155897897-2a0d936e-bb19-4d25-a924-3b417591738a.png)

I can see the above error when trying to open the details of some packages with a mouse right-click. Oddly, the error does not happen when opening the details with a double click. More oddly, I can observe it only with some particular packages. So far I have experienced this behavior with: `openorienteering-mapper`, `qgis`, `putty`.
After clicking "OK", Chocolatey GUI crashes for good and must be started over.
There is a side-issue, which might or might not be related: After starting the Chocolatey GUI again, the invalid package (the one on its details the Chocolatey GUI crashed) cannot be found with the search-box in the remote packages view.

### What is Expected?
Details page opens and no error happens.

### How Did You Get This To Happen? (Steps to Reproduce)
1. I opened Chocolatey GUI and then "chocolatey" (list of remote packages)
2. I searched for "QGIS"
3. I right-clicked the "QGIS" package and selected "Details"
4. The "System.Exception" happened

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19043.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1320
* Chocolatey version (Run `choco --version`): 0.12.1

### Output Log
not relevant I think, see the screenshot on the top

**Comment by CicadaCinema** [comment]
<img width="1167" alt="Untitled" src="https://user-images.githubusercontent.com/52425971/162868679-93583adb-13e8-416f-889a-3b1f01625e97.png">

I'm getting the same error

**Comment by aleks648** [comment]
![image](https://user-images.githubusercontent.com/11696336/163069882-ae1ac456-f56c-42ee-9d5a-a74bbbab0868.png)

I'm getting the same also. Steps to reproduce. Open details of a package not installed by chocolately but already installed on the system, go back then reopen details. Specifically Brave and Telegram in my case.

System Details
OS Build: 10.0.19043.0
Windows PowerShell version: 5.1.19041.1320
Chocolatey version: 1.1.0

**Comment by RicME85** [comment]
I am getting this error. As with OP I am getting it when right-clicking and going to details on programs.

**Comment by fraynaud33** [comment]
problem still present with chocolatey GUI 1.1.2

**Comment by Ethanadams642** [comment]
Issue still present but triggers when getting details on some remote packages.

Chocolatey gui v2.1.0.0

**Comment by ScrubN** [comment]
Just ran into this myself.

I can reliably reproduce by opening the details page on any package, then opening the details page specifically on the grammarly package. That includes opening the grammarly details page twice.

It seems you *must* use the context menu to open the details page instead of double-click.

![image](https://github.com/chocolatey/ChocolateyGUI/assets/72096833/477f286d-bba1-4765-8de2-471086898443)

Chocolatey GUI v2.1.0.0

**Comment by graham-collinson** [comment]
Seeing this issue on one of my systems when right clicking for details.

    OS Build (In PowerShell run [System.Environment]::OSVersion.version.tostring()): 10.0.22000.0
    Windows PowerShell version (Run: $PSVersionTable): 5.1.22000.2003
    Chocolatey version (Run choco --version): 2.2.2
gui version 2.1.0

---------------------------
Unhandled Exception
---------------------------
System.Exception: Method Pin on type MS.Internal.NamedObject does not have a valid method signature. The method must have one of the following signatures: 'public void Pin()' or 'public void Pin(object parameter)'
   at ChocolateyGui.Common.Windows.Commands.CommandExecutionManager.CommandExecutionProvider`1..ctor(Type targetType, String canExecuteMethodName, String executedMethodName) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Commands\CommandExecutionManager.cs:line 338
   at lambda_method(Closure )
   at ChocolateyGui.Common.Windows.Commands.CommandExecutionManager.GetCommandExecutionProvider(Object target, String canExecuteMethodName, String executedMethodName) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Commands\CommandExecutionManager.cs:line 174
   at ChocolateyGui.Common.Windows.Commands.CommandExecutionManager.TryExecuteCommand(Object target, Object parameter, Boolean execute, String executedMethodName, String canExecuteMethodName, Boolean& canExecute) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Commands\CommandExecutionManager.cs:line 141
   at ChocolateyGui.Common.Windows.Commands.DataContextCommandAdapter.System.Windows.Input.ICommand.CanExecute(Object parameter) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Commands\DataContextCommandAdapter.cs:line 102
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ChocolateyGui.App.Main(String[] args) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui\App.xaml.cs:line 122
