### ISSUE TITLE
Clicking on settings gives ArgumentNullException

### ISSUE THREAD

**Issue by ImportTaste** [chocolatey/ChocolateyGUI#931]
### What You Are Seeing?
![image](https://user-images.githubusercontent.com/53661808/160886653-4b698522-99d9-47ac-92cb-cd1f8d6bd4d5.png)
```
System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at ChocolateyGui.Common.Windows.ViewModels.SettingsViewModel.<OnActivated>d__100.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\ViewModels\SettingsViewModel.cs:line 615
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ChocolateyGui.App.Main(String[] args) in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui\App.xaml.cs:line 122
```

### What is Expected?
For settings to load.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Open Chocolatey GUI
2. Click settings on the top right

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19044.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1620
* Chocolatey version (Run `choco --version`): 1.1.0

### Output Log
<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2022-03-30 11:39:24.633 -05:00 [Information] chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2022-03-30 11:39:27.354 -05:00 [Fatal] Unhandled Exception
~~~

</p>

</details>

I can provide a crash dump if necessary.

**Comment by gep13** [comment]
@ImportTaste can you please provide some additional information here...

Is this a fresh installation of Chocolatey GUI, or have you upgraded from a previous version?  If so, what version?

Is the system that you are running on using a locale of something other than English?  If so, what locale is it configured to use?

**Comment by gep13** [comment]
And just to confirm, what version of Chocolatey GUI are you installing?  The latest? Version 1.0.0.

**Comment by ImportTaste** [comment]
> And just to confirm, what version of Chocolatey GUI are you installing? The latest? Version 1.0.0.

1.0.0

**Comment by gep13** [comment]
Are you a Chocolatey Business user, or are you using only the OSS packages?

Could you provide the output from the following command:

```
choco list -lo
```

**Comment by ImportTaste** [comment]
> Are you a Chocolatey Business user, or are you using only the OSS packages?
> 
> Could you provide the output from the following command:
> 
> ```
> choco list -lo
> ```

I'm an OSS user.

```
Chocolatey v1.1.0
3proxy 0.9.3
autohotkey 1.1.33.10
autohotkey.install 1.1.33.10
avisynthplus 3.7.2
bulk-crap-uninstaller 5.2
choco-cleaner 0.0.8.4
chocolatey 1.1.0
chocolatey-core.extension 1.3.5.1
chocolatey-dotnetfx.extension 1.0.1
chocolatey-windowsupdate.extension 1.0.4
chocolateygui 1.0.0
curl 7.82.0
disable-nvidia-telemetry 1.1.0.20190306
dngrep 3.0.42.0
dotnet 6.0.3
dotnet-5.0-runtime 5.0.15
dotnet-6.0-desktopruntime 6.0.3
dotnet-6.0-runtime 6.0.3
dotnet-desktopruntime 6.0.3
dotnet-runtime 6.0.3
DotNet3.5 3.5.20160716
DotNet4.5.2 4.5.2.20140902
DotNet4.6 4.6.00081.20150925
dotnetcore-3.1-desktopruntime 3.1.23
dotnetcore-desktopruntime 3.1.23
dotnetfx 4.8.0.20190930
etcher 1.7.8
exiftool 12.40
fastcopy.portable 4.1.3
FirefoxESR 91.7.1
fzf 0.29.0
git 2.35.1.2
git.install 2.35.1.2
golang 1.18
gsudo 1.2.0
honeyview.install 5.46
hugo 0.96.0
hwinfo 7.22
hwinfo.install 7.22
ilspy 7.2
jre8 8.0.321
KB2533623 2.0.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
keepass 2.50
keepass.install 2.50
keepass.portable 2.50
kitty 0.74.4.13
LinkShellExtension 3.9.3.5
llvm 14.0.0
Ln 2.9.3.3
netch 2020.3.5-pre
netfx-4.6.2 4.6.2.20210905
netfx-4.7.2 4.7.2.0
nirlauncher 1.23.56
nodejs-lts 16.14.2
nsis 3.08
nsis.install 3.08
nvidia-display-driver 512.15
nvidia-inspector 2.3.0.20200706
nvidia-profile-inspector 2.3.0.10
pandoc 2.17.1.1
pet 0.4.0
pping 3.0.0
python 3.10.4
python3 3.10.4
qbittorrent 4.4.2
ruby 3.1.1.1
ruby.install 3.1.1.1
rufus 3.18
snoop 4.0.1
streamlink 3.2.0
SwissFileKnife 1.9.8.0
sysinternals 2022.2.16
tortoisegit 2.13.0.1
tortoisesvn 1.14.2.29370
trid 2.24.20220327
vcredist140 14.31.31103
vcredist2010 10.0.40219.32503
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
vidcutter 6.0.5.1
vscodium.install 1.65.2
windowsdriverkit10 10.0.19041.685
winrar 6.11
wkhtmltopdf 0.12.6.20210114
xnviewmp.install 0.99.7
yarn 1.22.15
yt-dlp 2022.03.08.1
```

**Comment by rsolo93** [comment]
I second this, seeing the same as a C4B customer. Fresh install of Chocolaty GUI with chocolateygui 1.1.0
chocolateygui.extension 1.0.0. 

What is Expected?
For settings to load.

How Did You Get This To Happen? (Steps to Reproduce)
Open Chocolatey GUI
Click settings on the top right
System Details
OS Build (In PowerShell run [System.Environment]::OSVersion.version.tostring()): 10.0.19044.0
Windows PowerShell version (Run: $PSVersionTable): 5.1.19041.1682
Chocolatey version (Run choco --version): 1.1.0

Output Log
<details open>
<summary>Full Log Output</summary>
<br>

2022-09-12 09:49:20.082 -04:00 [Information] No branding files exist, nothing else to be done
2022-09-12 09:49:25.733 -04:00 [Information] chocolatey.licensed - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2022-09-12 09:49:26.056 -04:00 [Information] Interal-repo - https://someInternalRepository (Authenticated)| Priority 1|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2022-09-12 09:49:33.701 -04:00 [Information] 7-zip|21.7|21.7|false
2022-09-12 09:49:34.960 -04:00 [Information] dell-controlvault-host-components|5.5.26.70|5.5.26.70|false
2022-09-12 09:49:35.664 -04:00 [Information] openssl|1.1.1.1700|1.1.1.1700|false
2022-09-12 09:49:38.505 -04:00 [Fatal] Unhandled Exception

</details>

**Comment by corbob** [comment]
Hi @ImportTaste and @rsolo93,

Could you try running `chocolateyguicli` from an administrative terminal and report back if there is any output? If there is, perhaps try running `chocolateyguicli feature` and `chocolateyguicli config` and report back the outputs?

**Comment by rsolo93** [comment]
Sure thing, 

chocolateyguicli feature
Chocolatey GUI v1.1.0.0 Business
[ ] AllowNonAdminAccessToSettings - Controls whether or not a non-administrator user can access the Settings Screen.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[x] DefaultToDarkMode - Default to dark mode. It is still possible to switch during use.
[x] DefaultToTileViewForLocalSource - Default to tile instead of list view. It is still possible to switch during use.
[x] DefaultToTileViewForRemoteSource - Default to tile instead of list view. It is still possible to switch during use.
[ ] ExcludeInstalledPackages - Do not show packages that are already installed when viewing sources.
[ ] HideAllRemoteChocolateySources - Controls whether or not remote sources (for example the Chocolatey Community Repository) are displayed in Chocolatey GUI.  Enabling this feature makes Chocolatey GUI a read-only application, that will only show the currently installed packages.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] HidePackageDownloadCount - Allows control over whether package download count is displayed on remote source views.
[x] HideThisPCSource - Controls whether or not the This PC source is displayed in Chocolatey GUI.  Enabling this feature means that Chocolatey GUI will no longer show a list of all the currently installed packages on the machine.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] PreventAllPackageIconDownloads - Prevents the download of the icon for all package. NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] PreventAutomatedOutdatedPackagesCheck - Prevents automated check for outdated packages on local and remote source views.
[ ] PreventPreload - Prevents preloading results with a blank search when opening the remote source view.
[ ] PreventUsageOfUpdateAllButton - Prevents the ability for user to use the Update All button. NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] ShowAdditionalPackageInformation - Show additional package information on Local and Remote views.
[ ] ShowAggregatedSourceView - Show additional source combining all sources in one place.
[ ] ShowConsoleOutput - Shows output from the commands being executed when a job is running.
[ ] SkipModalDialogConfirmation - Skip modal dialog confirmations when performing potentially destructive actions.
[ ] UseDelayedSearch - Enables live search, which returns results after a short delay without clicking the search button.
[x] UseKeyboardBindings - Allows keyboard bindings to be used to interact with different areas of the Chocolatey GUI User Interface.

chocolateyguicli config
Chocolatey GUI v1.1.0.0 Business
DefaultSourceName =  - The name of the source which should be shown by default when opening application. NOTE: This configuration setting will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
OutdatedPackagesCacheDurationInMinutes = 60 - Default timeout for outdated packages to be cached.  Default is 60 minutes.
UseLanguage = en-US - The preferred language for Chocolatey GUI. Defaults to Windows System Locale.

**Comment by Sympatron** [comment]
What is the status of this issue? It seems to be unresolved still. I am an OSS user and I get the same exact error.

It points to [this function](https://github.com/chocolatey/ChocolateyGUI/blob/a0082c2b58c2850f133aa682538eb1912cd4fac4/Source/ChocolateyGui.Common.Windows/ViewModels/SettingsViewModel.cs#L577), but I can't figure out which line. Line 627 can't be it, because `GetString()` is not called there. I can't find any reference to `GetString()` so it must be called indirectly...

My config:
OS: Win 10
System locale: de
```
❯ chocolateyguicli feature
Chocolatey GUI v2.0.0.0
[ ] AllowNonAdminAccessToSettings - Controls whether or not a non-administrator user can access the Settings Screen.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] DefaultToDarkMode - Default to dark mode. It is still possible to switch during use.
[x] DefaultToTileViewForLocalSource - Default to tile instead of list view. It is still possible to switch during use.
[x] DefaultToTileViewForRemoteSource - Default to tile instead of list view. It is still possible to switch during use.
[ ] ExcludeInstalledPackages - Do not show packages that are already installed when viewing sources.
[ ] HideAllRemoteChocolateySources - Controls whether or not remote sources (for example the Chocolatey Community Repository) are displayed in Chocolatey GUI.  Enabling this feature makes Chocolatey GUI a read-only application, that will only show the currently installed packages.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] HidePackageDownloadCount - Allows control over whether package download count is displayed on remote source views.
[ ] HideThisPCSource - Controls whether or not the This PC source is displayed in Chocolatey GUI.  Enabling this feature means that Chocolatey GUI will no longer show a list of all the currently installed packages on the machine.  NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] PreventAllPackageIconDownloads - Prevents the download of the icon for all package. NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] PreventAutomatedOutdatedPackagesCheck - Prevents automated check for outdated packages on local and remote source views.
[ ] PreventPreload - Prevents preloading results with a blank search when opening the remote source view.
[ ] PreventUsageOfUpdateAllButton - Prevents the ability for user to use the Update All button. NOTE: This feature will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
[ ] ShowAdditionalPackageInformation - Show additional package information on Local and Remote views.
[ ] ShowAggregatedSourceView - Show additional source combining all sources in one place.
[ ] ShowConsoleOutput - Shows output from the commands being executed when a job is running.
[ ] SkipModalDialogConfirmation - Skip modal dialog confirmations when performing potentially destructive actions.
[ ] UseDelayedSearch - Enables live search, which returns results after a short delay without clicking the search button.
[x] UseKeyboardBindings - Allows keyboard bindings to be used to interact with different areas of the Chocolatey GUI User Interface.

❯ chocolateyguicli config
Chocolatey GUI v2.0.0.0
DefaultSourceName =  - The name of the source which should be shown by default when opening application. NOTE: This configuration setting will only work with Chocolatey for Business and the Chocolatey GUI licensed extension installed.
OutdatedPackagesCacheDurationInMinutes = 60 - Default timeout for outdated packages to be cached.  Default is 60 minutes.
UseLanguage = en-US - The preferred language for Chocolatey GUI. Defaults to Windows System Locale.
```
My error message:
![image](https://github.com/chocolatey/ChocolateyGUI/assets/35803463/fc540d5b-b965-458e-8cf3-b8f7932cb1c4)

**Comment by rsolo93** [comment]
This has been resolved. The issue stemmed from setting a chocolatey
licensed only option in the config before adding the chocolatey licensed
extension and license

**Comment by Sympatron** [comment]
Do you mean PR #1010? When will this be available via chocolatey?

**Comment by gep13** [comment]
A new version of Chocolatey GUI (v2.1.0-alpha-20230608) has been released which aims to address this issue.  You can find the release notes here:

https://docs.chocolatey.org/en-us/chocolatey-gui/release-notes#alpha-20230608-june-8-2023

And the package here:

https://community.chocolatey.org/packages/chocolateygui/2.1.0-alpha-20230608

You should be able to upgrade to this package version using:

```
choco upgrade chocolateygui --pre
```

If you could take this for a spin, and verify that the issue is now resolved, that would be very helpful.
